sudo: false

language: node_js

node_js:
  - 4

addons:
  firefox:
    "latest"

before_script:
  # Make sure we have new NPM.
  - npm install -g npm
  - npm install -g grunt-cli
  - npm config set loglevel warn
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
