sudo: false

language: node_js

node_js:
  - 4

addons:
  firefox:
    "latest"

before_install:
  # Make sure we have new NPM.
  - npm install -g npm
  - npm config set loglevel warn

after_install:
  - npm install -g grunt-cli
  - npm install -g protractor@4.0.3
  - webdriver-manager update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
